#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://mygdrive.projectlegionos.workers.dev/0:/ccache/legion-vanilla/ccache.tar.gz # Where cccahe is located, use your ones, from where you want to download ccache!

cd /tmp # Where to download cccahe
time rclone copy drive:ccache/legion-vanilla/ccache.tar.gz /tmp/
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the upload ccache process
