#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/project-legionos/manifest.git -b 11 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

git clone https://github.com/legionos-devices/device_xiaomi_miatoll.git -b 11 device/xiaomi/miatoll

git clone https://github.com/legionos-devices/device_xiaomi_sm6250-common.git -b 11 device/xiaomi/sm6250-common

git clone --depth=1 https://github.com/legionos-devices/vendor_xiaomi_miatoll.git vendor/xiaomi/miatoll

git clone --depth=1 https://github.com/legionos-devices/vendor_xiaomi_sm6250-common.git vendor/xiaomi/sm6250-common

git clone --depth=1 https://github.com/legionos-devices/kernel_xiaomi_sm6250.git kernel/xiaomi/sm6250
